---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: canonical-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box 
    require_chef_omnibus: 11.4.4 
    customize:
      memory: 2048
  run_list:
  - recipe[apt]
- name: ubuntu-10.04
  driver_config:
    box: opscode-ubuntu-10.04
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-10.04_chef-11.2.0.box 
    require_chef_omnibus: 11.4.4 
    customize:
      memory: 2048
  run_list:
  - recipe[apt]
- name: centos-6.3
  driver_config:
    box: opscode-centos-6.3
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box 
    require_chef_omnibus: 11.4.4
    customize:
      memory: 2048
  run_list:
  - recipe[yum::epel]
- name: centos-5.8
  driver_config:
    box: opscode-centos-5.8
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.3_chef-11.2.0.box
    require_chef_omnibus: 11.4.4
    customize:
      memory: 2048
  run_list:
  - recipe[yum::epel]
suites:
- name: default
  run_list: 
  - recipe[minitest-handler]
  - recipe[vagrant_test]
  attributes: {}
- name: plugin_lwrp
  run_list:
  - recipe[vagrant_test]
  - recipe[vagrant_test::plugins]
  - recipe[vagrant_test::boxes]
  attributes: {}
